### PR TITLE
CASSANDRA-10786 workaround

### PR DESCRIPTION
**Pull request by dcheckoway**
This is a workaround for https://issues.apache.org/jira/browse/CASSANDRA-10786, where the server reuses the identical Query ID for a given statement even if the result set metadata has changed.  The lengthy comments in `cqerl_cache.erl` explain the situation in detail.

Since `cqerl_cache` is not currently a shared cache (each `cqerl_client` has its own "silo" within the cache), we need a way to invalidate (and force a reprepare of) cached queries that were already reprepared by a different connection to the same node.

If you add a new column, this is what happens on other connections to that node:
```
{function_clause,[{lists,zip,[[<<"ÿÿÿÿ">>],[]],[{file,"lists.erl"},{line,386}]},{lists,zip,2,[{file,"lists.erl"},{line,386}]},{lists,zip,2,[{file,"lists.erl"},{line,386}]},{cqerl_protocol,decode_proplist_row,3,[{file,"src/cqerl_protocol.erl"},{line,739}]},{cqerl,'-all_rows/2-lc$^0/1-0-',3,[{file,"src/cqerl.erl"},{line,295}]},...
```
(note that `<<"ÿÿÿÿ">>` is `0xFFFFFFFF` or -1)

If you remove a column, this happens:
```
{function_clause,[{lists,zip,[[],[{cqerl_result_column_spec,<<"keyspace_name">>,<<"table_name">>,existing_column,timestamp}]],[{file,"lists.erl"},{line,386}]},{lists,zip,2,[{file,"lists.erl"},{line,386}]},{lists,zip,2,[{file,"lists.erl"},{line,386}]},{cqerl_protocol,decode_proplist_row,3,[{file,"src/cqerl_protocol.erl"},{line,739}]},{cqerl,'-all_rows/2-lc$^0/1-0-',3,[{file,"src/cqerl.erl"},{line,295}]},...
```

NOTE: I was only able to test this using v3 protocol against 2.1.9, but I'm pretty sure it's an issue all the way up through v4.

### CODE REVIEW

**Comment by dcheckoway** [comment]
@matehat fwiw, we literally _just_ switched back to the `matehat` fork the other day (and celebrated accordingly).  But schema changes are something we can't avoid, and without this change `cqerl` gets into a mode where it continues using cached stale metadata, and the only remedy is restarting the app.  That causes down time for us because the entire cluster experiences a flood of the same exact issue at the same time, and we have to roll all of them (meanwhile our clients get `503`s).  We've dreaded schema changes for this reason.

Anyway, this is an important fix for us since we make schema changes on a pretty regular basis and this lets us do it seamlessly.  I'm anxious to get your feedback, if not a merge (we can continue using our fork but obviously prefer not to).

**Comment by bernardd** [comment]
Thanks very much for the patch. Forgive me if the answer to this is obvious, but given this:
```
"Note that the prepared query ID returned is global to the node on which the query
 has been prepared. It can be used on any connection to that node
 until the node is restarted (after which the query must be reprepared)."
```
Might it not be simpler (and more efficient) to tweak the cache system so that it's keyed off the host/port rather than the client pid? It's been a little while since I took a close look, but my (quite possibly incorrect) assumption had always been that the prepared query ID was local to the connection, not the node. If this isn't the case, we can probably simplify stuff a good deal by doing what I suggested. It seems, at a glance, like it would both solve this problem and result in a smaller cache set.

**Comment by dcheckoway** [comment]
@bernardd I agree completely about a shared cache (see my comments in `cqerl_cache.erl`).  That said, that would be a pervasive change.  In the interest of time and keeping risk low for now, until somebody has time to revamp the cache, this PR's fix seems a reasonable stopgap.

**Comment by dcheckoway** [comment]
Poke!  Curious if you guys are onboard with this workaround as a near term solution.

**Comment by bernardd** [comment]
Sorry, I've been on holidays for the last week and a bit. Unless I'm much mistaken, I don't think a fix for the cache system will be very much work at all, and it seems like a better solution in pretty much all respects. Give me a couple of days to catch up and I'll take a look at doing that, and keep this as a backup option. Unless, of course, @matehat has a differing opinion in which case he gets the final say :)

**Comment by bernardd** [comment]
Sorry all - I haven't had a chance to look at this yet and probably won't for at least the next week or so. @matehat if you're happy to take this change then go ahead and merge it - I can't see any problem with it. If we come up with a better solution later we can always replace it.

**Comment by matehat** [comment]
I'm ok with this, at least until we put a better solution in place! Sorry for the delay @dcheckoway !

**Comment by bernardd** [comment]
I've just pushed a commit to the v2.0-pre branch that improves the cache as I described above (sorry it took so long). See https://github.com/matehat/cqerl/pull/114
I don't know how cleanly it will merge to 1.0 but you're more than welcome to try :)

**Pull request merged**
